### ISSUE TITLE
Meta Weeks of Contribution Task

### ISSUE THREAD

**Issue by MozillaTN** [MozillaTN/mozillatn.github.io#2]
- [x] Blog post about Weeks Of Contribution  - @iamVP7  on June 4th

_Syllabus_
- [x] Localization syllabus @jskcse4  on 8th June 
- [x] SUMO Syllabus @hellokarthic   on 15th June 
- [x]  Firefox Nightly QA by @AmdAdam  on 22th June
- [x]  Add-ons Developmebt Syllabus @iamVP7  on 29th June 

_Design the Mentor Collection Form_
http://goo.gl/forms/h4ScnTIGFVDOOpH73

_Training Date_
- [x] June 29th - Localization  by @jskcse4 
- [x] July 13th - Firefox Nigthly (QA) by @AmdAdam
- [x]  July 27th - SUMO by  @hellokarthic
- [ ] August 10th - Add-ons (using Webextension API) by @iamVP7 

_Consolidated Blog post_
- [x] August 2nd - Localization  by @jskcse4 
- [ ] August 10th - Firefox Nigthly (QA) by @AmdAdam
- [ ]  September 15th - SUMO by  @hellokarthic
- [ ] August 30th - Add-ons (using Webextension API) by @iamVP7
